config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'homes#top'
  
  get'about'=> 'homes#about'

  resources :books

  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  belongs_to :user
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
  end

  def show
    @book = Book.find(params[:id])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    @book.save
    redirect_to book_path(@book)
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.all
    @book　= Book.new
  end


  private
  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/index.html.erb
<h1>Books#index</h1>
<p>Find me in app/views/books/index.html.erb</p>

app/views/homes/about.html.erb
<h1 class="text-center mt-4">Welcome to Bookers!</h1>

app/views/homes/top.html.erb
<div class="container">
  <div class="row">
    <div class="col-5 mx-auto">
      <h1 class="mt-3">welcome to Bookers !!</h1>
      <p>In Bookers,</p>
      <p>you can share and exchange your opinions , inpressions , and emotions about various books!</p>

      <div><%= link_to "Log In", new_user_session_path, class: "btn btn-info btn-sm btn-block mb-3" %></div>
      <div><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-sm btn-block" %></div>
    </div>
  </div>
</div>

app/views/layouts/_prf.html.erb
<h2>User info</h2>


<h2>New Book</h2>
<%= form_with model: book, local:true do |f| %>
  <div>Title</div>
  <%= f.text_field :title %>
  <div class="pt-3">Opinion</div>
  <%= f.text_area :body %>
  <br>
  <%= f.submit 'Create Book', class: "btn btn-success" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlusBookres</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <div class="container">
        <div class="navbar-brand"><%= link_to "Bookers", root_path %></div>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav ml-auto">
            <% if user_signed_in? %>
              <li class="mr-2"><%= link_to "Home", user_path(current_user) %></li>
              <li class="mr-2"><%= link_to "User", users_path %></li>
              <li class="mr-2"><%= link_to "Book", users_path %></li>
              <li class="mr-2"><%= link_to "logout", destroy_user_session_path, method: :delete %></li>
            <% else %>
              <li class="mr-2"><%= link_to "Home", root_path %></li>
              <li class="mr-2"><%= link_to "About", about_path %></li>
              <li class="mr-2"><%= link_to "Sign Up", new_user_registration_path %></li>
              <li class="mr-2"><%= link_to "Log In", new_user_session_path %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
    <div class="container mt-5">
      <div class="row">
        <div class="mx-auto">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/show.html.erb
<div class="container">
  <div class="row mt-3">
    <div class="col-4">
      <%= render 'layouts/prf', user: current_user, book: Book.new %>
    </div>

    <div class="col">
      <h2>Books</h2>
      <table class="table">
        <tr>
          <th class="text-center", style="width:30%">Title</th>
          <th style="width:70%">Opinion</th>
        </tr>
        <tr>
          <% @books.each do |book| %>
            <th><%= book.title %></th>
            <th><%= book.body %></th>
          <% end %>
        </tr>
      </table>
    </div>
  </div>
</div>